name: "Test"
on:
  pull_request:
  merge_group:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v7
      - name: Install Nix
        uses: cachix/install-nix-action@v31
      - run: nix flake check
